NeosGameStore.WebUI/Models/CartIndexViewModel.cs
using NeosGameStore.Domain.Entities;

namespace NeosGameStore.WebUI.Models
{
    public class CartIndexViewModel
    {
        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; }
    }
}

NeosGameStore.WebUI/Models/GamesListViewModel.cs
using NeosGameStore.Domain.Entities;
using System.Collections.Generic;

namespace NeosGameStore.WebUI.Models
{
    public class GamesListViewModel
    {
        public IEnumerable<Game> Games { get; set; }
        public PagingInfo PagingInfo { get; set; }
        public string CurentCategory { get; set; }
    }
}

NeosGameStore.WebUI/Models/PagingInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NeosGameStore.WebUI.Models
{
    public class PagingInfo
    {
        public int TotalItems { get; set; }

        public int ItemsPerPage { get; set; }

        public int CurrentPage { get; set; }

        public int TotalPages
        {
            get
            {
                return (int)Math.Ceiling((decimal)TotalItems / ItemsPerPage);
            }
        }

    }
}

NeosGameStore.WebUI/Controllers/CartController.cs
using NeosGameStore.Domain.Abstract;
using NeosGameStore.Domain.Entities;
using NeosGameStore.WebUI.Models;
using System.Linq;
using System.Web.Mvc;

namespace NeosGameStore.WebUI.Controllers
{
    public class CartController : Controller
    {
        private IGameRepository repository;
        public CartController(IGameRepository repo)
        {
            repository = repo;
        }

        public ActionResult Index(string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = this.GetCart(),
                ReturnUrl = returnUrl
            });
        }

        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }

        public RedirectToRouteResult AddToCart(int gameId, string returnUrl)
        {
            Game game = repository.Games.FirstOrDefault(g => g.GameId == gameId);

            if (game != null)
            {
                this.GetCart().AddItem(game, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart(int gameId, string returnUrl)
        {
            Game game = repository.Games.FirstOrDefault(g => g.GameId == gameId);

            if (game != null)
            {
                GetCart().RemoveLine(game);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public Cart GetCart()
        {
            Cart cart = (Cart)Session["Cart"];
            if (cart == null)
            {
                cart = new Cart();
                Session["Cart"] = cart;
            }
            return cart;
        }

    }
}

NeosGameStore.WebUI/Controllers/GameController.cs
using NeosGameStore.Domain.Abstract;
using NeosGameStore.Domain.Entities;
using NeosGameStore.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NeosGameStore.WebUI.Controllers
{
    public class GameController : Controller
    {
        IGameRepository repository;
        public int pageSize = 4;

        public GameController(IGameRepository repository)
        {
            this.repository = repository;
        }

        public ActionResult List(string category, int page = 1)
        {
            GamesListViewModel model = new GamesListViewModel()
            {
                Games = repository.Games
                .Where(p => category == null || p.Category == category)
                .OrderBy(game => game.GameId)
                .Skip((page - 1) * pageSize)
                .Take(pageSize),
                PagingInfo = new PagingInfo()
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = category == null ?
                    repository.Games.Count():
                    repository.Games.Where(game=>game.Category==category).Count()
                },
                CurentCategory = category
            };

            return View(model);
        }
    }
}

NeosGameStore.WebUI/Controllers/NavController.cs
using NeosGameStore.Domain.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NeosGameStore.WebUI.Controllers
{
    public class NavController : Controller
    {
        private IGameRepository repository;

        public NavController(IGameRepository repo)
        {
            repository = repo;
        }

        public PartialViewResult Menu(string category=null)
        {
            ViewBag.SelectedCategory = category;

            IEnumerable<string> categories = repository.Games
                .Select(game => game.Category)
                .Distinct()
                .OrderBy(x => x);
            return PartialView(categories);
        }
    }
}

NeosGameStore.WebUI/Views/Cart/Index.cshtml
@model NeosGameStore.WebUI.Models.CartIndexViewModel

@{
    ViewBag.Title = "NeosGameStore: your cart";
}
<style>
    #cartTable td {
        vertical-align: middle;
    }
</style>
<h2>Ваша корзина</h2>
<table class="table">
    <thead>
        <tr>
            <th>Quantity</th>
            <th>Game</th>
            <th class="text-right">Price</th>
            <th class="text-right">Summary:</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var line in Model.Cart.Lines)
        {
            <tr>
                <td class="text-center">@line.Quantity</td>
                <td class="text-left">@line.Game.Name</td>
                <td class="text-right">@line.Game.Price.ToString("# $")</td>
                <td class="text-right">
                    @((line.Quantity * line.Game.Price).ToString("# $"))
                </td>
                <td>
                    @using (Html.BeginForm("RemoveFromCart", "Cart"))
                    {
                        @Html.Hidden("GameId", line.Game.GameId)
                        @Html.HiddenFor(x => x.ReturnUrl)
                        <input class="btn btn-sm btn-warning" type="submit" value="Remove" />
                    }
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Sum:</td>
            <td class="text-right">
                @Model.Cart.ComputeTotalValue().ToString("# $")
            </td>
        </tr>
    </tfoot>
</table>

<div class="text-center">
    <a class="btn btn-primary" href="@Model.ReturnUrl">Continue buying</a>
</div>

NeosGameStore.WebUI/Views/Cart/Summary.cshtml
@model NeosGameStore.Domain.Entities.Cart

<div class="navbar-right">
    @Html.ActionLink("Order", "Index", "Cart",
    new { returnUrl = Request.Url.PathAndQuery },
    new { @class = "btn btn-default navbar-btn" })
</div>

<div class="navbar-text navbar-right">
    <b>Your Cart:</b>
    @Model.Lines.Sum(x => x.Quantity) games,
    @Model.ComputeTotalValue().ToString("# $")
</div>

NeosGameStore.WebUI/Views/Game/GameSummary.cshtml
@model NeosGameStore.Domain.Entities.Game

<div class="well">
    <h3>
        <strong>@Model.Name</strong>
        <span class="pull-right label label-primary">@Model.Price.ToString("# $")</span>
    </h3>
    @using (Html.BeginForm("AddToCart", "Cart"))
    {
        <div class="pull-right">
            @Html.HiddenFor(x=>x.GameId)
            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
            <input type="submit" class="btn btn-success" value="Add to Cart" />
        </div>
    }
    <span class="lead">@Model.Description</span>
</div>

NeosGameStore.WebUI/Views/Game/List.cshtml
@using NeosGameStore.WebUI.Models
@using NeosGameStore.WebUI.HtmlHelpers
@model GamesListViewModel

@{
    ViewBag.Title = "Products";
}

@foreach (var p in Model.Games)
{
    @Html.Partial("GameSummary",p)
}

<div class="btn-group pull-right">
    @Html.PageLinks(Model.PagingInfo, x => Url.Action("List", new { page = x, category = Model.CurentCategory }))
</div>

NeosGameStore.WebUI/Views/Nav/Menu.cshtml
@model IEnumerable<string>

@Html.ActionLink("Home", "List", "Game", null,
    new { @class = "btn btn-block btn-default btn-lg" })

@foreach (var link in Model)
{
    @Html.RouteLink(link, new
{
    controller = "Game",
    action = "List",
    category = link,
    page = 1
}, new
{
    @class = "btn btn-block btn-default btn-lg"
     +(link == ViewBag.SelectedCategory ? " btn-primary" : "")
})
}

NeosGameStore.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="navbar navbar-inverse" role="navigation">
        <div class="pull-left">
            <img src="~/Content/img/logo.png" alt="logo" width="50" height="50"/>
        </div>
        <a class="navbar-brand" href="#">NeosGameStore - shop of computer games</a>
        @Html.Action("Summary", "Cart")
    </div>
    <div class="row panel">
        <div id="categories" class="col-xs-3">
            @Html.Action("Menu", "Nav")
        </div>
        <div class="col-xs-8">
            @RenderBody()
        </div>
    </div>
</body>
</html>